### ISSUE TITLE
Config file paths are relative to current working directory instead of config file location

### ISSUE THREAD

**Issue by brianray** [EducationalTestingService/skll#213]
These may be windows related. However, two things I ran into so far one small and the other will need more investigation.

a) The path issue

```pytb
C:\Users\brray\Documents\GitHub\skll\examples>run_experiment titanic/evaluate_tuned.cfg
Traceback (most recent call last):
  File "C:\Users\brray\AppData\Local\Continuum\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\brray\AppData\Local\Continuum\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\brray\AppData\Local\Continuum\Anaconda\Scripts\run_experiment.exe\__main__.py", line 9, in <module>
  File "C:\Users\brray\AppData\Local\Continuum\Anaconda\lib\site-packages\skll\utilities\run_experiment.py", line 108, in main
    ablation=ablation, resume=args.resume)
  File "C:\Users\brray\AppData\Local\Continuum\Anaconda\lib\site-packages\skll\experiments.py", line 1052, in run_configuration
    custom_learner_path) = _parse_config_file(config_file)
  File "C:\Users\brray\AppData\Local\Continuum\Anaconda\lib\site-packages\skll\experiments.py", line 459, in _parse_config_file
    "config file does not exist"), train_path)
IOError: [Errno 2] The training path specified in the config file does not exist: u'train'
```

If I 'cd' into the titanic directory, it works.

**Comment by desilinguist** [comment]
Addressed by #246.
