### ISSUE TITLE
Problems running run_experiment on Windows with 2.7

### ISSUE THREAD

**Issue by brianray** [EducationalTestingService/skll#214]
This is the second issue (may also be windows related)

b) anaconda forking (I get hundreds of the following) when running `$ run_experiment titanic/evaluate_tuned.cfg`

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\brray\AppData\Local\Continuum\Anaconda\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Users\brray\AppData\Local\Continuum\Anaconda\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
```

**Comment by desilinguist** [comment]
I am going to close this for now since we haven't had any more reports about this.
