### ISSUE TITLE
error during the skll installation in conda environment

### ISSUE THREAD

**Issue by cml54** [EducationalTestingService/skll#232]
Hi,

while installing skll 1.0.1 on osx, I got the following error:
```
Traceback (most recent call last):
  File "/Users/clee001/anaconda/envs/py34/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/clee001/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    import logging
  File "/Users/clee001/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    def execute(args, parser):
  File "/Users/clee001/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 276, in install
    pkgs = sorted(r.get_pkgs(MatchSpec(name)))
  File "/Users/clee001/anaconda/lib/python2.7/site-packages/conda/plan.py", line 419, in execute_actions
    
  File "/Users/clee001/anaconda/lib/python2.7/site-packages/conda/plan.py", line 401, in execute_plan
    
  File "/Users/clee001/anaconda/lib/python2.7/site-packages/conda/plan.py", line 357, in link
    pinfile = join(prefix, 'conda-meta', 'pinned')
  File "/Users/clee001/anaconda/lib/python2.7/site-packages/conda/install.py", line 438, in link
    isfile(join(pkgs_dir, dn, 'info', 'index.json'))))
  File "/Users/clee001/anaconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    subprocess.check_call(['cmd', '/c', 'rd', '/s', '/q', path])
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text bin/compute_eval_from_predictions'
```

When I checked `has_prefix` files of 0.27 and 1.0.1 in skll conda package, I found that the file in 1.0.1 contains `/opt/anaconda1anaconda2anaconda3 text bin/` as prefixes instead of `bin/` in 0.27. 
I wonder if the difference caused the error.

**Comment by dan-blanchard** [comment]
That's really bizarre.  Sounds like a problem with the conda package (or the version of conda you're using).  Those prefixes should be replaced on installation.

**Comment by cml54** [comment]
the error occurred in using anaconda as conda manager. I can't remember the
version of the anaconda because the manager was broken during update.
I changed my conda manager to miniconda3 3.9.1. Then, the error is gone in
the new environment.
