### ISSUE TITLE
print_model_weights does not work for Logistic Regression models without intercepts.

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#250]
Here's the error I get:

```python
Traceback (most recent call last):
  File "/Users/nmadnani/anaconda/envs/garbage/bin/print_model_weights", line 6, in <module>
    sys.exit(main())
  File "/Users/nmadnani/anaconda/envs/garbage/lib/python3.4/site-packages/skll/utilities/print_model_weights.py", line 55, in main
    (weights, intercept) = learner.model_params
  File "/Users/nmadnani/anaconda/envs/garbage/lib/python3.4/site-packages/skll/learner.py", line 712, in model_params
    intercept = dict(zip(label_list, self.model.intercept_))
TypeError: zip argument #2 must support iteration
```

**Comment by dan-blanchard** [comment]
Fixed by #251.
