### ISSUE TITLE
print_model_weights no longer works with SVR models

### ISSUE THREAD

**Issue by mulhod** [EducationalTestingService/skll#257]
In previous versions, I had been able to use `print_model_weights` with SVR models, but now I get the following type of error:

```$ print_model_weights --k 0 some-model.model
Traceback (most recent call last):
  File ".../print_model_weights", line 6, in <module>
    sys.exit(main())
  File ".../lib/python3.4/site-packages/skll/utilities/print_model_weights.py", line 55, in main
    (weights, intercept) = learner.model_params
  File ".../lib/python3.4/site-packages/skll/learner.py", line 717, in model_params
    ).format(self._model_type))
ValueError: <class 'skll.learner.RescaledSVR'> is not supported by model_params with its current settings.```

I'm not sure if this is just no longer possible or if there's a bug. I don't see why we wouldn't be able to look into the SVR models, though, so the latter seems more likely.

**Comment by mulhod** [comment]
Never mind, this seemed to just be caused by some mixup in my conda environment.
