### ISSUE TITLE
Misleading error message when config file name is empty

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/skll#275]
Running `run_experiment " " ` leads to the following error message which is misleading about the nature of the problem and confusingly seems to reference older specs for the config file:
```
Traceback (most recent call last):
  File "/home/aloukina/miniconda3/envs/rsmtool/bin/run_experiment", line 6, in <module>
    sys.exit(main())
  File "/home/aloukina/miniconda3/envs/rsmtool/lib/python3.4/site-packages/skll/utilities/run_experiment.py", line 108, in main
    ablation=ablation, resume=args.resume)
  File "/home/aloukina/miniconda3/envs/rsmtool/lib/python3.4/site-packages/skll/experiments.py", line 697, in run_configuration
    custom_learner_path) = _parse_config_file(config_file)
  File "/home/aloukina/miniconda3/envs/rsmtool/lib/python3.4/site-packages/skll/config.py", line 247, in _parse_config_file
    raise ValueError("Configuration file does not contain experiment_name "
ValueError: Configuration file does not contain experiment_name in the [Input] section.
```
Passing empty line instead of the config file can happen when one (incorrectly) generates a number of jobs programmatically, so it would be good to catch this.

**Comment by desilinguist** [comment]
Addressed by #281.
