### ISSUE TITLE
Unclear error message when join a feature-set which contains only id and label

### ISSUE THREAD

**Issue by nailuenlai** [EducationalTestingService/skll#317]
In configuration files if one of **featuresets** files contains only two columns, which is **id** and **label**, **run_experiment** fails with unclear error message:
```
ValueError: blocks[:,0] is all None
```

Here is an simple example to illustrate this error.
Two tiny feature-set files:
```
local user$ cat some_feature.csv
id,foo
0,0
1,0
local user$ cat label.csv
id,label
0,0
1,1
```
**join_features** fails with unclear error message at first glance:
```
(myenv)local user$ join_features -i id -l label label.csv some_feature.csv joined.csv
Loading label.csv...           done
Loading some_feature.csv...           done
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/myenv/bin/join_features", line 11, in <module>
    sys.exit(main())
  File "/Users/user/miniconda3/envs/myenv/lib/python3.5/site-packages/skll/utilities/join_features.py", line 100, in main
    merged_set += fs
  File "/Users/user/miniconda3/envs/myenv/lib/python3.5/site-packages/skll/data/featureset.py", line 185, in __add__
    'csr')
  File "/Users/user/miniconda3/envs/myenv/lib/python3.5/site-packages/scipy/sparse/construct.py", line 456, in hstack
    return bmat([blocks], format=format, dtype=dtype)
  File "/Users/user/miniconda3/envs/myenv/lib/python3.5/site-packages/scipy/sparse/construct.py", line 585, in bmat
    raise ValueError('blocks[:,%d] is all None' % bcol_lengths.argmin())
ValueError: blocks[:,0] is all None
```
The SKLL version is 1.2
```
(myenv)local user$ join_features --version
join_features 1.2
```

**Comment by desilinguist** [comment]
`join_features` is meant to be used to join two files that contain different features for the same instances, i.e., the instances should have the same IDs and labels in the two files. So, this is not really a proper use of `join_features`. For example, if `foo.csv` looks like:

```
id,a,b,label
1,1,1,1
2,2,2,2
```

and `bar.csv` looks like :
```
id,c,d,label
1,1,1,1
2,2,2,2
```

then, running `join_features -l label foo.csv bar.csv baz.csv` yields the following output in `baz.csv`:

```
a,b,c,d,id,y
1.0,1.0,1.0,1.0,1,1
2.0,2.0,2.0,2.0,2,2
```

(the columns are alphabetically ordered)
