### ISSUE TITLE
ValueError: blocks[:,1] is all None

### ISSUE THREAD

**Issue by ssingh016** [EducationalTestingService/skll#324]
I'm trying to train a LinearRegression model with `run_experiment `using a number of feature sets. I'm getting the following error and am confused by what the problem could be. Is this a known issue?

>  File "/opt/python/3.4/lib/python3.4/site-packages/gridmap/job.py", line 219, in execute
    self.ret = self.function(*self.args, **self.kwlist)
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/experiments.py", line 391, in _classify_featureset
    num_features=hasher_features)
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/experiments.py", line 303, in _load_featureset
    merged_set += fs
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/data/featureset.py", line 185, in __add__
    'csr')
  File "/opt/python/3.4/lib/python3.4/site-packages/scipy/sparse/construct.py", line 464, in hstack
    return bmat([blocks], format=format, dtype=dtype)
  File "/opt/python/3.4/lib/python3.4/site-packages/scipy/sparse/construct.py", line 593, in bmat
    raise ValueError('blocks[:,%d] is all None' % bcol_lengths.argmin())
ValueError: blocks[:,1] is all None

> Traceback (most recent call last):
  File "/opt/python/3.4/bin/run_experiment", line 6, in <module>
    sys.exit(skll.utilities.run_experiment.main())
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/utilities/run_experiment.py", line 108, in main
    ablation=ablation, resume=args.resume)
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/experiments.py", line 890, in run_configuration
    temp_dir=log_path)
  File "/opt/python/3.4/lib/python3.4/site-packages/gridmap/job.py", line 806, in process_jobs
    monitor.check(sid, jobs)
  File "/opt/python/3.4/lib/python3.4/site-packages/gridmap/job.py", line 403, in check
    self.check_if_alive()
  File "/opt/python/3.4/lib/python3.4/site-packages/gridmap/job.py", line 460, in check_if_alive
    raise job.ret
ValueError: blocks[:,1] is all None

**Comment by aoifecahill** [comment]
Turns out that some feature files had all-0 values.
