### ISSUE TITLE
run_experiment3 throwing an error

### ISSUE THREAD

**Issue by bndgyawali** [EducationalTestingService/skll#351]
I get the following error while running `run_experiment3`

```
$ run_experiment3 config.cfg 
2017-05-26 08:51:33,129 - gridmap.job - ERROR - --------------------------------------------------------------------------------
2017-05-26 08:51:33,129 - gridmap.job - ERROR - GridMap job traceback for file_id.jsonlines_LogisticRegression:
2017-05-26 08:51:33,130 - gridmap.job - ERROR - --------------------------------------------------------------------------------
2017-05-26 08:51:33,130 - gridmap.job - ERROR - Exception: KeyError
2017-05-26 08:51:33,130 - gridmap.job - ERROR - Job ID: 5722453
2017-05-26 08:51:33,130 - gridmap.job - ERROR - Host: hostname
2017-05-26 08:51:33,130 - gridmap.job - ERROR - ................................................................................
2017-05-26 08:51:33,131 - gridmap.job - ERROR - Traceback (most recent call last):
  File "/opt/python/3.4/lib/python3.4/site-packages/gridmap/job.py", line 219, in execute
    self.ret = self.function(*self.args, **self.kwlist)
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/experiments.py", line 445, in _classify_featureset
    learning_curve_cv_folds = args.pop("learning_curve_cv_folds")
KeyError: 'learning_curve_cv_folds'

Traceback (most recent call last):
  File "/opt/python/3.4/bin/run_experiment3", line 6, in <module>
    sys.exit(skll.utilities.run_experiment.main())
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/utilities/run_experiment.py", line 108, in main
    ablation=ablation, resume=args.resume)
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/experiments.py", line 891, in run_configuration
    temp_dir=log_path)
  File "/opt/python/3.4/lib/python3.4/site-packages/gridmap/job.py", line 806, in process_jobs
    monitor.check(sid, jobs)
  File "/opt/python/3.4/lib/python3.4/site-packages/gridmap/job.py", line 403, in check
    self.check_if_alive()
  File "/opt/python/3.4/lib/python3.4/site-packages/gridmap/job.py", line 460, in check_if_alive
    raise job.ret
KeyError: 'learning_curve_cv_folds'
```

But, if I run locally, it completes without error 
```
$ run_experiment3 -l config.cfg 
Loading training.jsonlines...           done
Loading testing.jsonlines...           done
2017-05-26 08:51:49,120 - skll.learner - WARNING - Training data will be shuffled to randomize grid search folds.  Shuffling may yield different results compared to scikit-learn.
2017-05-26 08:52:03,099 - skll.learner - WARNING - There is mismatch between the training model features and the data passed to predict.
```

**Comment by desilinguist** [comment]
Please attach the config file.

**Comment by bndgyawali** [comment]
Here's how my config file looks like
```
[General]
experiment_name=exp_name
task=evaluate

[Input]
train_file=../skll_input/training.jsonlines
test_directory=../skll_input/testing.jsonlines
learners=["LogisticRegression"]

[Tuning]
grid_search=true
objective=accuracy

[Output]
probability=true
results=../skll_output
log=../skll_output
predictions=../skll_output
models=../skll_output
```

**Comment by desilinguist** [comment]
This is due to mismatching `skll` versions between the submitting node and the node that actually gets the job via `gridmap` so not a bug in SKLL.
