### ISSUE TITLE
Bug in SKLL when generating learning curves via gridmap

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#386]
Tested with the `learning_curve.cfg` file for the Titanic example included with SKLL. Running it locally works fine but running it on the grid yields the following error:

```
Traceback (most recent call last):
  File "/scratch/nmadnani/skllenv/bin/run_experiment", line 11, in <module>
    load_entry_point('skll', 'console_scripts', 'run_experiment')()
  File "/private/scratch/nmadnani/skll/skll/utilities/run_experiment.py", line 124, in main
    log_level=log_level)
  File "/private/scratch/nmadnani/skll/skll/experiments.py", line 1117, in run_configuration
    _check_job_results(job_results)
  File "/private/scratch/nmadnani/skll/skll/experiments.py", line 1154, in _check_job_results
    if not result_dicts or 'task' not in result_dicts[0]:
KeyError: 0
```

**Comment by desilinguist** [comment]
Addressed by #390.
