### ISSUE TITLE
Learner object has no attribute 'logger' in 1.5.1

### ISSUE THREAD

**Issue by benbuleong** [EducationalTestingService/skll#412]
When trying to run `generate_predictions` in v1.5.1 given the correct path to model and feature files, there is the following error:

```
Traceback (most recent call last):
  File "/XXX/bin/generate_predictions", line 11, in <module>
    sys.exit(main())
  File "/XXX/lib/python3.6/site-packages/skll/utilities/generate_predictions.py", line 167, in main
    for pred in predictor.predict(feature_set):
  File "/XXX/lib/python3.6/site-packages/skll/utilities/generate_predictions.py", line 68, in predict
    preds = self._learner.predict(data)
  File "/XXX/lib/python3.6/site-packages/skll/learner.py", line 1711, in predict
    self.logger.warning("There is mismatch between the training model "
AttributeError: 'Learner' object has no attribute 'logger'
```

I think it might be related to #406 and #407 ?

**Comment by desilinguist** [comment]
Hmm, If it’s what I suspect it is then you should have the same problem
with v1.5 too. Can you confirm?

**Comment by desilinguist** [comment]
This is a symptom of a larger issue and should be present in v1.5 as well. See #413 for more details. While I work on a fix, you can modify your installed copy of `generate_predictions.py` with the workaround mentioned there so that at least your work is not blocked.

**Comment by benbuleong** [comment]
It works now, but there seems to be another issue. When running `generate_predictions model_file feature1 feature2 ... `, it generated as many predictions as there are instances in each of the feature files. Isn't it the case that all feature files be indexed by the same set of instances, and only a final set of predictions for these instances based on all feature sets be generated? Using the `predict` mode in SKLL configuration and setting `featuresets = [["feature1","feature2", ...]]` did not have this issue.

**Comment by desilinguist** [comment]
I am confused. Are you saying that the actual behavior of `generate_predictions` has changed since the last version?

**Comment by benbuleong** [comment]
I have not used `generate_predictions` until SKLL 1.5.1, so I am not sure. But, logically speaking, I thought that it should behave in the same way as `run_experiment` with `prediction` mode based on the same learner and training/testing datasets. It looks like it is not in this case.

**Comment by desilinguist** [comment]
@benbuleong I don't think you are interpreting `generate_predictions` correctly. `generate_predictions` asks for an `input_file` not a feature file. It uses all of the features in that input file to make predictions. You cannot specify multiple feature files and group them in a set. If you want to use featuresets, use the `predict` task and a config file.

Can you please approve the PR if the error in this issue is resolved?

**Comment by desilinguist** [comment]
Thanks!
